esphome:
  name: sensor_chuva_rain_seer
  platform: ESP8266
  board: d1_mini

captive_portal:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: Rain Seer Sensor
    password: !secret SenhaAPI

logger:

ota:

api:

binary_sensor:
  - platform: gpio
    pin: 
      number: D1
      mode: INPUT_PULLUP
    name: "Rain Seer Sensor"

