esphome:
  name: sensor_chuva_piscina
  platform: ESP32
  board: esp32doit-devkit-v1
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.25.161
    gateway: 192.168.25.1
    subnet: 255.255.255.0

api:

logger:

ota:
  safe_mode: true
  password: animal
  
captive_portal:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO35
      inverted: true
    name: "Sensor de Chuva"